image: node:lts

cache:
  paths:
  - build

stages:
  - build
  - upload

build:
  stage: build
  script:
    - npm ci
    - cp src/.DefaultConfig.js src/Config.js
    - sed 's/$(GOOGLE_CLIENT_ID)/$GOOGLE_CLIENT_ID/g' src/Config.js
    - CI=false REACT_APP_CURRENT_GIT_SHA=$CI_COMMIT_SHORT_SHA npm run build
  artifacts:
    paths:
    - build

.upload_template: &upload_template
  stage: upload
  script:
    - mkdir -p ~/.ssh
    - which ssh-agent || ( apk --update add openssh-client )
    - eval $(ssh-agent -s)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - scp  -r build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

upload-prod:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PROD
  only:
    - tags

upload-preview:
  <<: *upload_template
  variables:
    DEPLOY_PATH: $DEPLOY_PATH_PREVIEW
  only:
    refs:
      - master
